rails authentications: Members only
mahmoud717/members-only pull request #1
Opened 2020-10-09 16:50 UTC by mahmoud717

in this project I created a rails app that does the following:
1- added authentication for users.
2- when a user is logged in he can create a post and see the other posts with the poster name.
3- if the user is not logged in he can only see the posts without any names.

---------------------------------------------------------------------------------------------------------------------------------------

there are some issues with the commit history that I had to neglect because I created the repo from a template that had to branches( master & development ) and worked on the development branch directly, because of that I can't merge them together because they have no common commit history.

i will take care of that the next time..

2020-10-09 19:06 UTC, lekegitrepo requested changes
## Status: Request changes :recycle:
### Good job :+1: However, you need to fix some issues and implement some missing requirements as mentioned in my comments :point_down:
**_(I would have added some of the following comment in the affected section of the commit history but it not available, due to a short commit history)_**

- **_Fix the configuration of the database it throws an error when I tried to run the migration command_**

- **_Remove all the logic from the views :point_down:_**

  * [ ] There should be NO application logic in the views (no `Post.new`, `Comment.create`, `current_user.friends.find_by(...)`...). Everything connected with data processing should be encapsulated in models and used in controllers.
  * [ ] View-related logic can be encapsulated in View helpers (app/helpers/\*_helper.rb)
  * [ ] There should be absolutely NO logic in views.

- **_Use `before_action` to restrict access to the `:new` and `:create` methods_**

#### _Reviewed by Temitayo Adeleke_

2020-10-09 21:25 UTC, mahmoud717 commented
- there are no errors happening when I try to run the migrations, not even on heruko.
- the only logic inside the views is using if statements and helpers predefined by the devise gem (user_signed_in?), and I added one called is_empty?.

2020-10-09 21:50 UTC, maelfosso requested changes
# Changes required :red_circle: 

Hello,

Thank you for making the suggested changes.
However, there are still some changes to do

1. Please, remove logic from views. Implement into view helpers

2. I got this error when launching your app
![Screenshot at 2020-10-09 22:48:15](https://user-images.githubusercontent.com/8848104/95634346-9a41e200-0a81-11eb-8b20-546a350393e7.png)

Also, this one
![Screenshot at 2020-10-09 22:49:24](https://user-images.githubusercontent.com/8848104/95634390-b6de1a00-0a81-11eb-8ac6-41dd921a0dcc.png)
Generally, helpers are defined for each controller

Kindly fix those bugs and submit a new code review request
Thanks

Mael FOSSO

2020-10-09 21:50 UTC, maelfosso commented on app/views/posts/index.html.erb
>      <%end %>
Remove logic from views.
Implement them in views helpers

2020-10-09 21:50 UTC, maelfosso commented on app/controllers/posts_controller.rb
>      @users = User.all
Why this variables?
You don't use it in the views, kindly remove it.

2020-10-10 13:33 UTC, mahmoud717 commented on app/controllers/posts_controller.rb
>      @users = User.all
because I'm creating posts on the index page so I have to have a post created to not get an error

2020-10-10 13:36 UTC, mahmoud717 commented on app/controllers/posts_controller.rb
>      @users = User.all
and the one in the new action isn't invoked unless I click create.
if I don't do that I'll get an error when I try to render the index page.

2020-10-10 18:38 UTC, closed without merging